AWSTemplateFormatVersion: "2010-09-09"
Description: "Dev environment - EC2 t3.medium with IAM role for SES + SSM"

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 key pair for initial SSH access (before Tailscale is set up)

  MyIP:
    Type: String
    Description: "Your public IP for SSH access (e.g. 203.0.113.50/32)"
    AllowedPattern: '(\d{1,3}\.){3}\d{1,3}/\d{1,2}'

Resources:
  # --- IAM ---
  DevInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dev-instance-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # Adjust these to match your project needs
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess

  DevInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: dev-instance-profile
      Roles:
        - !Ref DevInstanceRole

  # --- Security Group ---
  DevSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Dev server - SSH from your IP only, lock down after Tailscale"
      GroupName: dev-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
          Description: "SSH from your IP"

  # --- EC2 Instance ---
  DevInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: !FindInMap [RegionAMI, !Ref "AWS::Region", AMI]
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref DevInstanceProfile
      SecurityGroupIds:
        - !GetAtt DevSecurityGroup.GroupId
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: dev-server

# Update the AMI ID for your region. Find the latest Ubuntu 24.04 AMI:
#   aws ec2 describe-images --owners 099720109477 \
#     --filters "Name=name,Values=ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*" \
#     --query 'Images | sort_by(@, &CreationDate) | [-1].[ImageId,Name]' \
#     --output text
Mappings:
  RegionAMI:
    us-east-1:
      AMI: ami-0136735c2bb5cf5bf  # Ubuntu 24.04 LTS 2026-02-03

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref DevInstance

  PublicIP:
    Description: Public IP (use for initial SSH, then switch to Tailscale)
    Value: !GetAtt DevInstance.PublicIp

  SSHCommand:
    Description: SSH command for initial access
    Value: !Sub "ssh -i ${KeyPairName}.pem ubuntu@${DevInstance.PublicIp}"
